//! # Protocol middleware code generation
//!
//! This module provides a method for generating middleware classes
//! for each protocol. These classes ferry the data from C++ to Rust
//! so that the interface at the ffi barrier is clean.
//!
//! Each C++ interface will host a Box<...> of one of these extensions
//! that it will use to call into the Rust code.
//!
//! use crate::cpp_builder::CppBuilder;

use crate::cpp_builder::sanitize_identifier;
use crate::helpers::format_wayland_interface_to_rust_extension_struct;

use super::helpers::snake_to_pascal;
use crate::protocol_parser::{
    InterfaceItem, WaylandArg, WaylandArgType, WaylandEvent, WaylandInterface, WaylandProtocol,
};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Produces the identifier of the Rust variant generated by `wayland-scanner`
/// for a given enum entry name.
///
/// This must mirror `wayland-scanner`'s naming exactly so that generated
/// variants can be referenced directly: the entry is converted to camel case,
/// prefixed with `_` when it starts with a digit, and (via the camel-case
/// conversion) prefixed with `_` when it collides with the `Self` keyword.
fn wayland_enum_variant_ident(entry_name: &str) -> String {
    let camel = snake_to_pascal(entry_name);
    let camel = if camel == "Self" {
        format!("_{camel}")
    } else {
        camel
    };
    if entry_name.chars().next().is_some_and(char::is_numeric) {
        format!("_{camel}")
    } else {
        camel
    }
}

/// Generates the `EnumFallback` trait plus one implementation per enum.
///
/// The trait provides `fallback()`, which yields an enum's fallback value.
/// Bitfields are generated as `bitflags` structs, so their fallback is the
/// empty set (`Self::empty()`). Other enums prefer the entry whose value is `0`
/// when one exists and otherwise use the first defined entry. In both cases the
/// generated variant is referenced directly, so there is no runtime conversion
/// and no panic path.
fn generate_enum_fallback_impls(protocols: &[WaylandProtocol]) -> TokenStream {
    let mut seen = std::collections::HashSet::new();
    let impls = protocols
        .iter()
        .flat_map(|protocol| &protocol.interfaces)
        .filter(|interface| interface.name != "wl_registry" && interface.name != "wl_display")
        .flat_map(|interface| {
            interface.items.iter().filter_map(move |item| {
                let InterfaceItem::Enum(e) = item else {
                    return None;
                };
                assert!(
                    !e.entries.is_empty(),
                    "Found enum '{}' with no entries, which is nonsensical and should never happen",
                    e.name
                );
                Some((interface.name.as_str(), e))
            })
        })
        .filter_map(|(interface_name, e)| {
            if !seen.insert((interface_name, e.name.as_str())) {
                return None;
            }
            let enum_name = snake_to_pascal(&e.name);
            let interface_ident = format_ident!("{interface_name}");
            let enum_ident = format_ident!("{enum_name}");
            let enum_path: syn::Path = syn::parse_quote!(#interface_ident::#enum_ident);
            let fallback_expr = if e.bitfield.unwrap_or(false) {
                // Bitfields are `bitflags` structs; the empty set is always valid.
                quote! { Self::empty() }
            } else {
                // Prefer the `0`-valued entry when present, otherwise the first
                // defined entry, and reference the generated variant directly.
                let entry = e
                    .entries
                    .iter()
                    .find(|entry| entry.value == 0)
                    .unwrap_or_else(|| e.entries.first().unwrap());
                let variant = format_ident!("{}", wayland_enum_variant_ident(&entry.name));
                quote! { Self::#variant }
            };
            Some(quote! {
                impl EnumFallback for #enum_path {
                    fn fallback() -> Self {
                        #fallback_expr
                    }
                }
            })
        });

    quote! {
        trait EnumFallback: Sized {
            fn fallback() -> Self;
        }

        #(#impls)*
    }
}

pub fn generate_wayland_interface_middleware(protocols: &Vec<WaylandProtocol>) -> TokenStream {
    // First, generate the imports.
    let use_imports: Vec<TokenStream> = protocols
        .iter()
        .flat_map(generate_use_imports_for_protocol)
        .collect();

    // Next, generate the C++ -> Rust side.
    //
    // Note that there is a complication here. Certain arguments will not
    // be able to be ferried directly from C++ to Rust. This is because the Rust
    // Wayland protocol methods take arguments that cannot be sent over the C++ -> Rust
    // boundary. To fix this, we first generate middleware structs that make it easy
    // to copy the data.
    let enum_fallback_impls = generate_enum_fallback_impls(protocols);
    let extensions = protocols.iter().flat_map(generate_extensions_for_protocol);

    quote! {
        #[allow(dead_code, unused_imports)]
        mod middleware {
            use crate::wayland_server_core::*;
            use wayland_server::protocol::*;
            use cxx::{CxxString, CxxVector};
            use std::os::unix::io::BorrowedFd;
            #(#use_imports)*

            #enum_fallback_impls

            #(#extensions)*
        }
    }
}

fn generate_use_imports_for_protocol(protocol: &WaylandProtocol) -> Vec<TokenStream> {
    let is_core_wayland = protocol.name == "wayland";
    protocol
        .interfaces
        .iter()
        .filter(|interface| interface.name != "wl_registry" && interface.name != "wl_display")
        .flat_map(|interface| {
            let (interface_struct_path, interface_module_path) = if is_core_wayland {
                let struct_path: syn::Path = syn::parse_str(&format!(
                    "wayland_server::protocol::{}::{}",
                    interface.name,
                    snake_to_pascal(&interface.name)
                ))
                .expect("Failed to parse full interface path");

                let module_path: syn::Path =
                    syn::parse_str(&format!("wayland_server::protocol::{}", interface.name,))
                        .expect("Failed to parse interface module path");

                (struct_path, module_path)
            } else {
                let struct_path: syn::Path = syn::parse_str(&format!(
                    "crate::protocols::{}::{}::{}",
                    protocol.name,
                    interface.name,
                    snake_to_pascal(&interface.name)
                ))
                .expect("Failed to parse full interface path");

                let module_path: syn::Path = syn::parse_str(&format!(
                    "crate::protocols::{}::{}",
                    protocol.name, interface.name,
                ))
                .expect("Failed to parse interface module path");

                (struct_path, module_path)
            };

            vec![
                quote! { use #interface_struct_path; },
                quote! { use #interface_module_path; },
            ]
        })
        .collect()
}

fn generate_extensions_for_protocol(protocol: &WaylandProtocol) -> TokenStream {
    protocol
        .interfaces
        .iter()
        .filter(|interface| interface.name != "wl_registry" && interface.name != "wl_display")
        .flat_map(generate_extension_for_interface)
        .collect()
}

fn generate_extension_for_interface(interface: &WaylandInterface) -> Option<TokenStream> {
    let event_extensions: Vec<TokenStream> = interface
        .items
        .iter()
        .filter_map(|item| match item {
            InterfaceItem::Event(event) => {
                Some(generate_extension_method_for_event(event, &interface.name))
            }
            _ => None,
        })
        .collect();

    let interface_name = format_ident!("{}", snake_to_pascal(&interface.name));
    let interface_name_ext = format_ident!(
        "{}",
        format_wayland_interface_to_rust_extension_struct(&interface.name)
    );
    Some(quote! {
        pub struct #interface_name_ext {
            pub wrapped: #interface_name
        }

        impl #interface_name_ext {
            pub fn post_error(&mut self, code: u32, message: &CxxString) {
                use wayland_server::Resource;
                if self.wrapped.is_alive() {
                    self.wrapped.post_error(
                        code,
                        message.to_string()
                    );
                }
            }

            pub fn version(&self) -> u32 {
                use wayland_server::Resource;
                self.wrapped.version()
            }

            pub fn object_id(&self) -> u32 {
                use wayland_server::Resource;
                self.wrapped.id().protocol_id()
            }

            pub fn destroy_and_delete(&self) {
                use wayland_server::Resource;
                if self.wrapped.is_alive() {
                    if let Some(handle) = wayland_server::Resource::handle(&self.wrapped).upgrade() {
                        let _ = handle.destroy_object::<crate::wayland_server_core::ServerState>(
                            &self.wrapped.id(),
                        );
                    }
                }
            }

            #(#event_extensions)*
        }
    })
}

fn generate_extension_method_for_event(event: &WaylandEvent, interface_name: &str) -> TokenStream {
    let event_name: syn::Ident = format_ident!("{}", sanitize_identifier(&event.name));
    let ffi_args: Vec<TokenStream> = event
        .args
        .iter()
        .map(|arg| {
            wayland_arg_to_ffi_rust_str(arg)
                .parse::<TokenStream>()
                .expect("Failed to parse argument as TokenStream")
        })
        .collect();

    let rust_args: Vec<TokenStream> = event
        .args
        .iter()
        .map(|arg| {
            wayland_arg_to_rust_param_str(arg, interface_name)
                .parse::<TokenStream>()
                .expect("Failed to parse argument as TokenStream")
        })
        .collect();

    // Sending an event whose target or object argument has been destroyed panics
    // wayland-backend ("Attempting to send an event with objects from wrong client"),
    // e.g. wl_keyboard.leave sent from the focused surface's own destruction path.
    // libwayland tolerated such events (clients ignore ids of zombie objects), so
    // match that by dropping the event instead. This should not happen, so log loudly
    // when it does rather than crashing the compositor.
    //
    // TODO: If we want a more "correct" Rust version in the future, we will need
    // to change the behavior of surface focus. The issue here is that we send out
    // a surface "leave" event on a surface that lost focus due to its own destruction.
    // This is not necessarily wrong (libwayland tolerates it!).
    let object_guards: Vec<TokenStream> = event
        .args
        .iter()
        .filter(|arg| matches!(arg.type_, WaylandArgType::Object))
        .map(|arg| {
            let name = format_ident!("{}", sanitize_identifier(&arg.name));
            let zombie_object_message = format!(
                "{}.{}: referenced object '{}' is no longer alive; dropping event",
                interface_name, event.name, arg.name
            );
            if arg.allow_null.unwrap_or(false) {
                quote! {
                    if let Some(__obj) = unsafe { #name.as_ref() } {
                        if !__obj.wrapped.is_alive() {
                            log::error!("{}", #zombie_object_message);
                            return;
                        }
                    }
                }
            } else {
                quote! {
                    if !#name.wrapped.is_alive() {
                        log::error!("{}", #zombie_object_message);
                        return;
                    }
                }
            }
        })
        .collect();

    // Generate the ffi code that will call into the underlying method that is defined on the object
    // The first item is the definition, and the second is the method declaration for the trait.
    // The object guards call `is_alive`, which is provided by the `Resource` trait, so bring
    // it into scope when there are any guards to emit.
    let resource_import = if object_guards.is_empty() {
        quote! {}
    } else {
        quote! { use wayland_server::Resource; }
    };
    quote! {
        pub fn #event_name(&mut self, #(#ffi_args),*) {
            #resource_import
            #(#object_guards)*
            self.wrapped.#event_name(#(#rust_args),*)
        }
    }
}

pub fn wayland_arg_to_ffi_rust_str(arg: &WaylandArg) -> String {
    let name = sanitize_identifier(&arg.name);
    let nullable = arg.allow_null.unwrap_or(false);
    let is_object = matches!(arg.type_, WaylandArgType::Object | WaylandArgType::NewId);
    let mut arg_str = match arg.type_ {
        WaylandArgType::Int => format!("{}: {}", name, "i32"),
        WaylandArgType::Uint => format!("{}: {}", name, "u32"),
        WaylandArgType::Fixed => format!("{}: {}", name, "f64"),
        WaylandArgType::String => format!("{}: {}", name, "&CxxString"),
        WaylandArgType::Object | WaylandArgType::NewId => {
            let ext = format_wayland_interface_to_rust_extension_struct(
                arg.interface.as_ref().expect("Object is missing interface"),
            );
            // A nullable object is passed as a raw pointer so that absence can be
            // represented by null. Neither `std::optional` nor `Option<&Box<_>>` can
            // cross the cxx FFI boundary, but a raw pointer can.
            if nullable {
                format!("{}: *const Box<{}>", name, ext)
            } else {
                format!("{}: &Box<{}>", name, ext)
            }
        }
        WaylandArgType::Array => format!("{}: {}", name, "&CxxVector<u8>"),
        WaylandArgType::Fd => format!("{}: {}", name, "i32"),
    };

    // Nullable non-object arguments are still ferried as a `(value, has_value)` pair,
    // since their value type can always be sent across the boundary.
    if nullable && !is_object {
        arg_str.push_str(&format!(", has_{}: bool", arg.name));
    }

    arg_str
}

fn wayland_arg_to_rust_param_str(arg: &WaylandArg, interface_name: &str) -> String {
    let name = sanitize_identifier(&arg.name);
    let mut param = match arg.type_ {
        WaylandArgType::Int | WaylandArgType::Uint | WaylandArgType::Fixed => name.clone(),
        WaylandArgType::String => format!("{}.to_string()", name),
        WaylandArgType::Object | WaylandArgType::NewId => format!("&{}.wrapped", name),
        WaylandArgType::Array => format!("{}.iter().cloned().collect()", name),
        WaylandArgType::Fd => format!("unsafe {{ BorrowedFd::borrow_raw({}) }}", name),
    };

    if let Some(e) = &arg.enum_ {
        let (enum_interface, enum_name) = e.split_once('.').unwrap_or((interface_name, e.as_str()));
        let rust_enum_path = format!("{}::{}", enum_interface, snake_to_pascal(enum_name));
        // The fallback must be lazy (`unwrap_or_else`) and resolved at runtime by the
        // enum's own `EnumFallback::fallback()`, since not every enum has a 0-valued entry.
        param = format!(
            "{}::try_from({}).unwrap_or_else(|_| <{} as EnumFallback>::fallback())",
            rust_enum_path, param, rust_enum_path
        );
    }

    if arg.allow_null.unwrap_or(false) {
        param = match arg.type_ {
            // The nullable object arrives as a raw pointer; dereference it to recover the
            // `Option<&wrapped>` the underlying Wayland method expects.
            WaylandArgType::Object | WaylandArgType::NewId => {
                format!("unsafe {{ {name}.as_ref() }}.map(|__opt| &__opt.wrapped)")
            }
            _ => format!("if has_{} {{ Some({}) }} else {{ None }}", arg.name, param),
        };
    }

    param
}
