/*
 * Generated by gdbus-codegen 2.56.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "logind-seat.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.login1.Seat
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:LogindSeat
 * @title: LogindSeat
 * @short_description: Generated C code for the org.freedesktop.login1.Seat D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-login1-Seat.top_of_page">org.freedesktop.login1.Seat</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.login1.Seat ---- */

static const _ExtendedGDBusMethodInfo _logind_seat_method_info_terminate =
{
  {
    -1,
    (gchar *) "Terminate",
    NULL,
    NULL,
    NULL
  },
  "handle-terminate",
  FALSE
};

static const _ExtendedGDBusArgInfo _logind_seat_method_info_activate_session_IN_ARG_unnamed_arg0 =
{
  {
    -1,
    (gchar *) "unnamed_arg0",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _logind_seat_method_info_activate_session_IN_ARG_pointers[] =
{
  &_logind_seat_method_info_activate_session_IN_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _logind_seat_method_info_activate_session =
{
  {
    -1,
    (gchar *) "ActivateSession",
    (GDBusArgInfo **) &_logind_seat_method_info_activate_session_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-activate-session",
  FALSE
};

static const _ExtendedGDBusArgInfo _logind_seat_method_info_switch_to_IN_ARG_unnamed_arg0 =
{
  {
    -1,
    (gchar *) "unnamed_arg0",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _logind_seat_method_info_switch_to_IN_ARG_pointers[] =
{
  &_logind_seat_method_info_switch_to_IN_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _logind_seat_method_info_switch_to =
{
  {
    -1,
    (gchar *) "SwitchTo",
    (GDBusArgInfo **) &_logind_seat_method_info_switch_to_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-switch-to",
  FALSE
};

static const _ExtendedGDBusMethodInfo _logind_seat_method_info_switch_to_next =
{
  {
    -1,
    (gchar *) "SwitchToNext",
    NULL,
    NULL,
    NULL
  },
  "handle-switch-to-next",
  FALSE
};

static const _ExtendedGDBusMethodInfo _logind_seat_method_info_switch_to_previous =
{
  {
    -1,
    (gchar *) "SwitchToPrevious",
    NULL,
    NULL,
    NULL
  },
  "handle-switch-to-previous",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _logind_seat_method_info_pointers[] =
{
  &_logind_seat_method_info_terminate,
  &_logind_seat_method_info_activate_session,
  &_logind_seat_method_info_switch_to,
  &_logind_seat_method_info_switch_to_next,
  &_logind_seat_method_info_switch_to_previous,
  NULL
};

static const GDBusAnnotationInfo _logind_seat_property_id_annotation_info_0 =
{
  -1,
  (gchar *) "org.freedesktop.DBus.Property.EmitsChangedSignal",
  (gchar *) "const",
  NULL
};

static const GDBusAnnotationInfo * const _logind_seat_property_id_annotation_info_pointers[] =
{
  &_logind_seat_property_id_annotation_info_0,
  NULL
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_id =
{
  {
    -1,
    (gchar *) "Id",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    (GDBusAnnotationInfo **) &_logind_seat_property_id_annotation_info_pointers
  },
  "id",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_active_session =
{
  {
    -1,
    (gchar *) "ActiveSession",
    (gchar *) "(so)",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "active-session",
  FALSE
};

static const GDBusAnnotationInfo _logind_seat_property_can_multi_session_annotation_info_0 =
{
  -1,
  (gchar *) "org.freedesktop.DBus.Property.EmitsChangedSignal",
  (gchar *) "const",
  NULL
};

static const GDBusAnnotationInfo * const _logind_seat_property_can_multi_session_annotation_info_pointers[] =
{
  &_logind_seat_property_can_multi_session_annotation_info_0,
  NULL
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_can_multi_session =
{
  {
    -1,
    (gchar *) "CanMultiSession",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    (GDBusAnnotationInfo **) &_logind_seat_property_can_multi_session_annotation_info_pointers
  },
  "can-multi-session",
  FALSE
};

static const GDBusAnnotationInfo _logind_seat_property_can_tty_annotation_info_0 =
{
  -1,
  (gchar *) "org.freedesktop.DBus.Property.EmitsChangedSignal",
  (gchar *) "const",
  NULL
};

static const GDBusAnnotationInfo * const _logind_seat_property_can_tty_annotation_info_pointers[] =
{
  &_logind_seat_property_can_tty_annotation_info_0,
  NULL
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_can_tty =
{
  {
    -1,
    (gchar *) "CanTTY",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    (GDBusAnnotationInfo **) &_logind_seat_property_can_tty_annotation_info_pointers
  },
  "can-tty",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_can_graphical =
{
  {
    -1,
    (gchar *) "CanGraphical",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "can-graphical",
  FALSE
};

static const GDBusAnnotationInfo _logind_seat_property_sessions_annotation_info_0 =
{
  -1,
  (gchar *) "org.freedesktop.DBus.Property.EmitsChangedSignal",
  (gchar *) "false",
  NULL
};

static const GDBusAnnotationInfo * const _logind_seat_property_sessions_annotation_info_pointers[] =
{
  &_logind_seat_property_sessions_annotation_info_0,
  NULL
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_sessions =
{
  {
    -1,
    (gchar *) "Sessions",
    (gchar *) "a(so)",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    (GDBusAnnotationInfo **) &_logind_seat_property_sessions_annotation_info_pointers
  },
  "sessions",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_idle_hint =
{
  {
    -1,
    (gchar *) "IdleHint",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "idle-hint",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_idle_since_hint =
{
  {
    -1,
    (gchar *) "IdleSinceHint",
    (gchar *) "t",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "idle-since-hint",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _logind_seat_property_info_idle_since_hint_monotonic =
{
  {
    -1,
    (gchar *) "IdleSinceHintMonotonic",
    (gchar *) "t",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "idle-since-hint-monotonic",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _logind_seat_property_info_pointers[] =
{
  &_logind_seat_property_info_id,
  &_logind_seat_property_info_active_session,
  &_logind_seat_property_info_can_multi_session,
  &_logind_seat_property_info_can_tty,
  &_logind_seat_property_info_can_graphical,
  &_logind_seat_property_info_sessions,
  &_logind_seat_property_info_idle_hint,
  &_logind_seat_property_info_idle_since_hint,
  &_logind_seat_property_info_idle_since_hint_monotonic,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _logind_seat_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.login1.Seat",
    (GDBusMethodInfo **) &_logind_seat_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_logind_seat_property_info_pointers,
    NULL
  },
  "seat",
};


/**
 * logind_seat_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-login1-Seat.top_of_page">org.freedesktop.login1.Seat</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
logind_seat_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_logind_seat_interface_info.parent_struct;
}

/**
 * logind_seat_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #LogindSeat interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
logind_seat_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "id");
  g_object_class_override_property (klass, property_id_begin++, "active-session");
  g_object_class_override_property (klass, property_id_begin++, "can-multi-session");
  g_object_class_override_property (klass, property_id_begin++, "can-tty");
  g_object_class_override_property (klass, property_id_begin++, "can-graphical");
  g_object_class_override_property (klass, property_id_begin++, "sessions");
  g_object_class_override_property (klass, property_id_begin++, "idle-hint");
  g_object_class_override_property (klass, property_id_begin++, "idle-since-hint");
  g_object_class_override_property (klass, property_id_begin++, "idle-since-hint-monotonic");
  return property_id_begin - 1;
}



/**
 * LogindSeat:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-login1-Seat.top_of_page">org.freedesktop.login1.Seat</link>.
 */

/**
 * LogindSeatIface:
 * @parent_iface: The parent interface.
 * @handle_activate_session: Handler for the #LogindSeat::handle-activate-session signal.
 * @handle_switch_to: Handler for the #LogindSeat::handle-switch-to signal.
 * @handle_switch_to_next: Handler for the #LogindSeat::handle-switch-to-next signal.
 * @handle_switch_to_previous: Handler for the #LogindSeat::handle-switch-to-previous signal.
 * @handle_terminate: Handler for the #LogindSeat::handle-terminate signal.
 * @get_active_session: Getter for the #LogindSeat:active-session property.
 * @get_can_graphical: Getter for the #LogindSeat:can-graphical property.
 * @get_can_multi_session: Getter for the #LogindSeat:can-multi-session property.
 * @get_can_tty: Getter for the #LogindSeat:can-tty property.
 * @get_id: Getter for the #LogindSeat:id property.
 * @get_idle_hint: Getter for the #LogindSeat:idle-hint property.
 * @get_idle_since_hint: Getter for the #LogindSeat:idle-since-hint property.
 * @get_idle_since_hint_monotonic: Getter for the #LogindSeat:idle-since-hint-monotonic property.
 * @get_sessions: Getter for the #LogindSeat:sessions property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-login1-Seat.top_of_page">org.freedesktop.login1.Seat</link>.
 */

typedef LogindSeatIface LogindSeatInterface;
G_DEFINE_INTERFACE (LogindSeat, logind_seat, G_TYPE_OBJECT)

static void
logind_seat_default_init (LogindSeatIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * LogindSeat::handle-terminate:
   * @object: A #LogindSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-login1-Seat.Terminate">Terminate()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call logind_seat_complete_terminate() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-terminate",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LogindSeatIface, handle_terminate),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * LogindSeat::handle-activate-session:
   * @object: A #LogindSeat.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_unnamed_arg0: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-login1-Seat.ActivateSession">ActivateSession()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call logind_seat_complete_activate_session() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-activate-session",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LogindSeatIface, handle_activate_session),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * LogindSeat::handle-switch-to:
   * @object: A #LogindSeat.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_unnamed_arg0: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchTo">SwitchTo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call logind_seat_complete_switch_to() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-switch-to",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LogindSeatIface, handle_switch_to),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /**
   * LogindSeat::handle-switch-to-next:
   * @object: A #LogindSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToNext">SwitchToNext()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call logind_seat_complete_switch_to_next() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-switch-to-next",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LogindSeatIface, handle_switch_to_next),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * LogindSeat::handle-switch-to-previous:
   * @object: A #LogindSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToPrevious">SwitchToPrevious()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call logind_seat_complete_switch_to_previous() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-switch-to-previous",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (LogindSeatIface, handle_switch_to_previous),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject properties for D-Bus properties: */
  /**
   * LogindSeat:id:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.Id">"Id"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("id", "Id", "Id", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:active-session:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.ActiveSession">"ActiveSession"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_variant ("active-session", "ActiveSession", "ActiveSession", G_VARIANT_TYPE ("(so)"), NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:can-multi-session:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanMultiSession">"CanMultiSession"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("can-multi-session", "CanMultiSession", "CanMultiSession", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:can-tty:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanTTY">"CanTTY"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("can-tty", "CanTTY", "CanTTY", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:can-graphical:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanGraphical">"CanGraphical"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("can-graphical", "CanGraphical", "CanGraphical", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:sessions:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.Sessions">"Sessions"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_variant ("sessions", "Sessions", "Sessions", G_VARIANT_TYPE ("a(so)"), NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:idle-hint:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleHint">"IdleHint"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("idle-hint", "IdleHint", "IdleHint", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:idle-since-hint:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleSinceHint">"IdleSinceHint"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint64 ("idle-since-hint", "IdleSinceHint", "IdleSinceHint", 0, G_MAXUINT64, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * LogindSeat:idle-since-hint-monotonic:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleSinceHintMonotonic">"IdleSinceHintMonotonic"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint64 ("idle-since-hint-monotonic", "IdleSinceHintMonotonic", "IdleSinceHintMonotonic", 0, G_MAXUINT64, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * logind_seat_get_id: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.Id">"Id"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use logind_seat_dup_id() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
logind_seat_get_id (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_id (object);
}

/**
 * logind_seat_dup_id: (skip)
 * @object: A #LogindSeat.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.Id">"Id"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
logind_seat_dup_id (LogindSeat *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "id", &value, NULL);
  return value;
}

/**
 * logind_seat_set_id: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.Id">"Id"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_id (LogindSeat *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "id", value, NULL);
}

/**
 * logind_seat_get_active_session: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.ActiveSession">"ActiveSession"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use logind_seat_dup_active_session() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
GVariant *
logind_seat_get_active_session (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_active_session (object);
}

/**
 * logind_seat_dup_active_session: (skip)
 * @object: A #LogindSeat.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.ActiveSession">"ActiveSession"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_variant_unref().
 */
GVariant *
logind_seat_dup_active_session (LogindSeat *object)
{
  GVariant *value;
  g_object_get (G_OBJECT (object), "active-session", &value, NULL);
  return value;
}

/**
 * logind_seat_set_active_session: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.ActiveSession">"ActiveSession"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_active_session (LogindSeat *object, GVariant *value)
{
  g_object_set (G_OBJECT (object), "active-session", value, NULL);
}

/**
 * logind_seat_get_can_multi_session: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanMultiSession">"CanMultiSession"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
logind_seat_get_can_multi_session (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_can_multi_session (object);
}

/**
 * logind_seat_set_can_multi_session: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanMultiSession">"CanMultiSession"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_can_multi_session (LogindSeat *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "can-multi-session", value, NULL);
}

/**
 * logind_seat_get_can_tty: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanTTY">"CanTTY"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
logind_seat_get_can_tty (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_can_tty (object);
}

/**
 * logind_seat_set_can_tty: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanTTY">"CanTTY"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_can_tty (LogindSeat *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "can-tty", value, NULL);
}

/**
 * logind_seat_get_can_graphical: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanGraphical">"CanGraphical"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
logind_seat_get_can_graphical (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_can_graphical (object);
}

/**
 * logind_seat_set_can_graphical: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.CanGraphical">"CanGraphical"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_can_graphical (LogindSeat *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "can-graphical", value, NULL);
}

/**
 * logind_seat_get_sessions: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.Sessions">"Sessions"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use logind_seat_dup_sessions() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
GVariant *
logind_seat_get_sessions (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_sessions (object);
}

/**
 * logind_seat_dup_sessions: (skip)
 * @object: A #LogindSeat.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.Sessions">"Sessions"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_variant_unref().
 */
GVariant *
logind_seat_dup_sessions (LogindSeat *object)
{
  GVariant *value;
  g_object_get (G_OBJECT (object), "sessions", &value, NULL);
  return value;
}

/**
 * logind_seat_set_sessions: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.Sessions">"Sessions"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_sessions (LogindSeat *object, GVariant *value)
{
  g_object_set (G_OBJECT (object), "sessions", value, NULL);
}

/**
 * logind_seat_get_idle_hint: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleHint">"IdleHint"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
logind_seat_get_idle_hint (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_idle_hint (object);
}

/**
 * logind_seat_set_idle_hint: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleHint">"IdleHint"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_idle_hint (LogindSeat *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "idle-hint", value, NULL);
}

/**
 * logind_seat_get_idle_since_hint: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleSinceHint">"IdleSinceHint"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint64 
logind_seat_get_idle_since_hint (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_idle_since_hint (object);
}

/**
 * logind_seat_set_idle_since_hint: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleSinceHint">"IdleSinceHint"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_idle_since_hint (LogindSeat *object, guint64 value)
{
  g_object_set (G_OBJECT (object), "idle-since-hint", value, NULL);
}

/**
 * logind_seat_get_idle_since_hint_monotonic: (skip)
 * @object: A #LogindSeat.
 *
 * Gets the value of the <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleSinceHintMonotonic">"IdleSinceHintMonotonic"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint64 
logind_seat_get_idle_since_hint_monotonic (LogindSeat *object)
{
  return LOGIND_SEAT_GET_IFACE (object)->get_idle_since_hint_monotonic (object);
}

/**
 * logind_seat_set_idle_since_hint_monotonic: (skip)
 * @object: A #LogindSeat.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-freedesktop-login1-Seat.IdleSinceHintMonotonic">"IdleSinceHintMonotonic"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
logind_seat_set_idle_since_hint_monotonic (LogindSeat *object, guint64 value)
{
  g_object_set (G_OBJECT (object), "idle-since-hint-monotonic", value, NULL);
}

/**
 * logind_seat_call_terminate:
 * @proxy: A #LogindSeatProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.Terminate">Terminate()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call logind_seat_call_terminate_finish() to get the result of the operation.
 *
 * See logind_seat_call_terminate_sync() for the synchronous, blocking version of this method.
 */
void
logind_seat_call_terminate (
    LogindSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Terminate",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * logind_seat_call_terminate_finish:
 * @proxy: A #LogindSeatProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to logind_seat_call_terminate().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with logind_seat_call_terminate().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_terminate_finish (
    LogindSeat *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_terminate_sync:
 * @proxy: A #LogindSeatProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.Terminate">Terminate()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See logind_seat_call_terminate() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_terminate_sync (
    LogindSeat *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Terminate",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_activate_session:
 * @proxy: A #LogindSeatProxy.
 * @arg_unnamed_arg0: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.ActivateSession">ActivateSession()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call logind_seat_call_activate_session_finish() to get the result of the operation.
 *
 * See logind_seat_call_activate_session_sync() for the synchronous, blocking version of this method.
 */
void
logind_seat_call_activate_session (
    LogindSeat *proxy,
    const gchar *arg_unnamed_arg0,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ActivateSession",
    g_variant_new ("(s)",
                   arg_unnamed_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * logind_seat_call_activate_session_finish:
 * @proxy: A #LogindSeatProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to logind_seat_call_activate_session().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with logind_seat_call_activate_session().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_activate_session_finish (
    LogindSeat *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_activate_session_sync:
 * @proxy: A #LogindSeatProxy.
 * @arg_unnamed_arg0: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.ActivateSession">ActivateSession()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See logind_seat_call_activate_session() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_activate_session_sync (
    LogindSeat *proxy,
    const gchar *arg_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ActivateSession",
    g_variant_new ("(s)",
                   arg_unnamed_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_switch_to:
 * @proxy: A #LogindSeatProxy.
 * @arg_unnamed_arg0: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchTo">SwitchTo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call logind_seat_call_switch_to_finish() to get the result of the operation.
 *
 * See logind_seat_call_switch_to_sync() for the synchronous, blocking version of this method.
 */
void
logind_seat_call_switch_to (
    LogindSeat *proxy,
    guint arg_unnamed_arg0,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SwitchTo",
    g_variant_new ("(u)",
                   arg_unnamed_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * logind_seat_call_switch_to_finish:
 * @proxy: A #LogindSeatProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to logind_seat_call_switch_to().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with logind_seat_call_switch_to().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_switch_to_finish (
    LogindSeat *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_switch_to_sync:
 * @proxy: A #LogindSeatProxy.
 * @arg_unnamed_arg0: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchTo">SwitchTo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See logind_seat_call_switch_to() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_switch_to_sync (
    LogindSeat *proxy,
    guint arg_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SwitchTo",
    g_variant_new ("(u)",
                   arg_unnamed_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_switch_to_next:
 * @proxy: A #LogindSeatProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToNext">SwitchToNext()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call logind_seat_call_switch_to_next_finish() to get the result of the operation.
 *
 * See logind_seat_call_switch_to_next_sync() for the synchronous, blocking version of this method.
 */
void
logind_seat_call_switch_to_next (
    LogindSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SwitchToNext",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * logind_seat_call_switch_to_next_finish:
 * @proxy: A #LogindSeatProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to logind_seat_call_switch_to_next().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with logind_seat_call_switch_to_next().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_switch_to_next_finish (
    LogindSeat *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_switch_to_next_sync:
 * @proxy: A #LogindSeatProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToNext">SwitchToNext()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See logind_seat_call_switch_to_next() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_switch_to_next_sync (
    LogindSeat *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SwitchToNext",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_switch_to_previous:
 * @proxy: A #LogindSeatProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToPrevious">SwitchToPrevious()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call logind_seat_call_switch_to_previous_finish() to get the result of the operation.
 *
 * See logind_seat_call_switch_to_previous_sync() for the synchronous, blocking version of this method.
 */
void
logind_seat_call_switch_to_previous (
    LogindSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SwitchToPrevious",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * logind_seat_call_switch_to_previous_finish:
 * @proxy: A #LogindSeatProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to logind_seat_call_switch_to_previous().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with logind_seat_call_switch_to_previous().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_switch_to_previous_finish (
    LogindSeat *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_call_switch_to_previous_sync:
 * @proxy: A #LogindSeatProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToPrevious">SwitchToPrevious()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See logind_seat_call_switch_to_previous() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
logind_seat_call_switch_to_previous_sync (
    LogindSeat *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SwitchToPrevious",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * logind_seat_complete_terminate:
 * @object: A #LogindSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-login1-Seat.Terminate">Terminate()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
logind_seat_complete_terminate (
    LogindSeat *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * logind_seat_complete_activate_session:
 * @object: A #LogindSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-login1-Seat.ActivateSession">ActivateSession()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
logind_seat_complete_activate_session (
    LogindSeat *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * logind_seat_complete_switch_to:
 * @object: A #LogindSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchTo">SwitchTo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
logind_seat_complete_switch_to (
    LogindSeat *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * logind_seat_complete_switch_to_next:
 * @object: A #LogindSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToNext">SwitchToNext()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
logind_seat_complete_switch_to_next (
    LogindSeat *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * logind_seat_complete_switch_to_previous:
 * @object: A #LogindSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-login1-Seat.SwitchToPrevious">SwitchToPrevious()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
logind_seat_complete_switch_to_previous (
    LogindSeat *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * LogindSeatProxy:
 *
 * The #LogindSeatProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * LogindSeatProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #LogindSeatProxy.
 */

struct _LogindSeatProxyPrivate
{
  GData *qdata;
};

static void logind_seat_proxy_iface_init (LogindSeatIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (LogindSeatProxy, logind_seat_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (LogindSeatProxy)
                         G_IMPLEMENT_INTERFACE (LOGIND_TYPE_SEAT, logind_seat_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (LogindSeatProxy, logind_seat_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (LOGIND_TYPE_SEAT, logind_seat_proxy_iface_init))

#endif
static void
logind_seat_proxy_finalize (GObject *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (logind_seat_proxy_parent_class)->finalize (object);
}

static void
logind_seat_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 9);
  info = _logind_seat_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
logind_seat_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.freedesktop.login1.Seat: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
logind_seat_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 9);
  info = _logind_seat_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.freedesktop.login1.Seat", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) logind_seat_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
logind_seat_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_logind_seat_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], LOGIND_TYPE_SEAT);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, LOGIND_TYPE_SEAT);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
logind_seat_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_logind_seat_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_logind_seat_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
logind_seat_proxy_get_id (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Id");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static GVariant *
logind_seat_proxy_get_active_session (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  GVariant *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "ActiveSession");
  value = variant;
  if (variant != NULL)
    g_variant_unref (variant);
  return value;
}

static gboolean 
logind_seat_proxy_get_can_multi_session (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CanMultiSession");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
logind_seat_proxy_get_can_tty (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CanTTY");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
logind_seat_proxy_get_can_graphical (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CanGraphical");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static GVariant *
logind_seat_proxy_get_sessions (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  GVariant *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Sessions");
  value = variant;
  if (variant != NULL)
    g_variant_unref (variant);
  return value;
}

static gboolean 
logind_seat_proxy_get_idle_hint (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "IdleHint");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static guint64 
logind_seat_proxy_get_idle_since_hint (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  guint64 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "IdleSinceHint");
  if (variant != NULL)
    {
      value = g_variant_get_uint64 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static guint64 
logind_seat_proxy_get_idle_since_hint_monotonic (LogindSeat *object)
{
  LogindSeatProxy *proxy = LOGIND_SEAT_PROXY (object);
  GVariant *variant;
  guint64 value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "IdleSinceHintMonotonic");
  if (variant != NULL)
    {
      value = g_variant_get_uint64 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
logind_seat_proxy_init (LogindSeatProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = logind_seat_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, LOGIND_TYPE_SEAT_PROXY, LogindSeatProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), logind_seat_interface_info ());
}

static void
logind_seat_proxy_class_init (LogindSeatProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = logind_seat_proxy_finalize;
  gobject_class->get_property = logind_seat_proxy_get_property;
  gobject_class->set_property = logind_seat_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = logind_seat_proxy_g_signal;
  proxy_class->g_properties_changed = logind_seat_proxy_g_properties_changed;

  logind_seat_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (LogindSeatProxyPrivate));
#endif
}

static void
logind_seat_proxy_iface_init (LogindSeatIface *iface)
{
  iface->get_id = logind_seat_proxy_get_id;
  iface->get_active_session = logind_seat_proxy_get_active_session;
  iface->get_can_multi_session = logind_seat_proxy_get_can_multi_session;
  iface->get_can_tty = logind_seat_proxy_get_can_tty;
  iface->get_can_graphical = logind_seat_proxy_get_can_graphical;
  iface->get_sessions = logind_seat_proxy_get_sessions;
  iface->get_idle_hint = logind_seat_proxy_get_idle_hint;
  iface->get_idle_since_hint = logind_seat_proxy_get_idle_since_hint;
  iface->get_idle_since_hint_monotonic = logind_seat_proxy_get_idle_since_hint_monotonic;
}

/**
 * logind_seat_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-login1-Seat.top_of_page">org.freedesktop.login1.Seat</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call logind_seat_proxy_new_finish() to get the result of the operation.
 *
 * See logind_seat_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
logind_seat_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (LOGIND_TYPE_SEAT_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.login1.Seat", NULL);
}

/**
 * logind_seat_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to logind_seat_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with logind_seat_proxy_new().
 *
 * Returns: (transfer full) (type LogindSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
LogindSeat *
logind_seat_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return LOGIND_SEAT (ret);
  else
    return NULL;
}

/**
 * logind_seat_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-login1-Seat.top_of_page">org.freedesktop.login1.Seat</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See logind_seat_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type LogindSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
LogindSeat *
logind_seat_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (LOGIND_TYPE_SEAT_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.login1.Seat", NULL);
  if (ret != NULL)
    return LOGIND_SEAT (ret);
  else
    return NULL;
}


/**
 * logind_seat_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like logind_seat_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call logind_seat_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See logind_seat_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
logind_seat_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (LOGIND_TYPE_SEAT_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.login1.Seat", NULL);
}

/**
 * logind_seat_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to logind_seat_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with logind_seat_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type LogindSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
LogindSeat *
logind_seat_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return LOGIND_SEAT (ret);
  else
    return NULL;
}

/**
 * logind_seat_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like logind_seat_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See logind_seat_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type LogindSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
LogindSeat *
logind_seat_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (LOGIND_TYPE_SEAT_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.login1.Seat", NULL);
  if (ret != NULL)
    return LOGIND_SEAT (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * LogindSeatSkeleton:
 *
 * The #LogindSeatSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * LogindSeatSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #LogindSeatSkeleton.
 */

struct _LogindSeatSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_logind_seat_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], LOGIND_TYPE_SEAT);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, LOGIND_TYPE_SEAT);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_logind_seat_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_logind_seat_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_logind_seat_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_logind_seat_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _logind_seat_skeleton_vtable =
{
  _logind_seat_skeleton_handle_method_call,
  _logind_seat_skeleton_handle_get_property,
  _logind_seat_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
logind_seat_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return logind_seat_interface_info ();
}

static GDBusInterfaceVTable *
logind_seat_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_logind_seat_skeleton_vtable;
}

static GVariant *
logind_seat_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_logind_seat_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _logind_seat_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _logind_seat_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _logind_seat_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.login1.Seat", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _logind_seat_emit_changed (gpointer user_data);

static void
logind_seat_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _logind_seat_emit_changed (skeleton);
}

static void logind_seat_skeleton_iface_init (LogindSeatIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (LogindSeatSkeleton, logind_seat_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (LogindSeatSkeleton)
                         G_IMPLEMENT_INTERFACE (LOGIND_TYPE_SEAT, logind_seat_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (LogindSeatSkeleton, logind_seat_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (LOGIND_TYPE_SEAT, logind_seat_skeleton_iface_init))

#endif
static void
logind_seat_skeleton_finalize (GObject *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  guint n;
  for (n = 0; n < 9; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (logind_seat_skeleton_parent_class)->finalize (object);
}

static void
logind_seat_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 9);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_logind_seat_emit_changed (gpointer user_data)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.freedesktop.login1.Seat",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_logind_seat_schedule_emit_changed (LogindSeatSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
logind_seat_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _logind_seat_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _logind_seat_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
logind_seat_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 9);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _logind_seat_schedule_emit_changed (skeleton, _logind_seat_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
logind_seat_skeleton_init (LogindSeatSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = logind_seat_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, LOGIND_TYPE_SEAT_SKELETON, LogindSeatSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 9);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_VARIANT);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[4], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[5], G_TYPE_VARIANT);
  g_value_init (&skeleton->priv->properties[6], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[7], G_TYPE_UINT64);
  g_value_init (&skeleton->priv->properties[8], G_TYPE_UINT64);
}

static const gchar *
logind_seat_skeleton_get_id (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static GVariant *
logind_seat_skeleton_get_active_session (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  GVariant *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_variant (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
logind_seat_skeleton_get_can_multi_session (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
logind_seat_skeleton_get_can_tty (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
logind_seat_skeleton_get_can_graphical (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[4]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static GVariant *
logind_seat_skeleton_get_sessions (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  GVariant *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_variant (&(skeleton->priv->properties[5]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
logind_seat_skeleton_get_idle_hint (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[6]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static guint64 
logind_seat_skeleton_get_idle_since_hint (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  guint64 value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint64 (&(skeleton->priv->properties[7]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static guint64 
logind_seat_skeleton_get_idle_since_hint_monotonic (LogindSeat *object)
{
  LogindSeatSkeleton *skeleton = LOGIND_SEAT_SKELETON (object);
  guint64 value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint64 (&(skeleton->priv->properties[8]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
logind_seat_skeleton_class_init (LogindSeatSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = logind_seat_skeleton_finalize;
  gobject_class->get_property = logind_seat_skeleton_get_property;
  gobject_class->set_property = logind_seat_skeleton_set_property;
  gobject_class->notify       = logind_seat_skeleton_notify;


  logind_seat_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = logind_seat_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = logind_seat_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = logind_seat_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = logind_seat_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (LogindSeatSkeletonPrivate));
#endif
}

static void
logind_seat_skeleton_iface_init (LogindSeatIface *iface)
{
  iface->get_id = logind_seat_skeleton_get_id;
  iface->get_active_session = logind_seat_skeleton_get_active_session;
  iface->get_can_multi_session = logind_seat_skeleton_get_can_multi_session;
  iface->get_can_tty = logind_seat_skeleton_get_can_tty;
  iface->get_can_graphical = logind_seat_skeleton_get_can_graphical;
  iface->get_sessions = logind_seat_skeleton_get_sessions;
  iface->get_idle_hint = logind_seat_skeleton_get_idle_hint;
  iface->get_idle_since_hint = logind_seat_skeleton_get_idle_since_hint;
  iface->get_idle_since_hint_monotonic = logind_seat_skeleton_get_idle_since_hint_monotonic;
}

/**
 * logind_seat_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-login1-Seat.top_of_page">org.freedesktop.login1.Seat</link>.
 *
 * Returns: (transfer full) (type LogindSeatSkeleton): The skeleton object.
 */
LogindSeat *
logind_seat_skeleton_new (void)
{
  return LOGIND_SEAT (g_object_new (LOGIND_TYPE_SEAT_SKELETON, NULL));
}

