flowchart TD
    PR{{Pull Request}} --> Builds(<a href="#mir-builds">Builds and tests</a>
                                  <a href="#unit-tests">unit</a>
                                  <a href="#acceptance-tests">acceptance</a>
                                  <a href="#integration-tests">integration</a>
                                  <a href="#performance-and-smoke-tests">performance</a>)
    PR --> Snaps(<a href="#downstream-snap-builds">Downstream snaps</a>)
    PR --> ABI(<a href="#abi-checks">ABI checks</a>)
    PR --> Coverage(<a href="#coverage-measurement">Coverage</a>)
    Merge{{Merge}} --> Builds
    Merge --> Coverage
    Merge --> Sanitizers(<a href="#sanitizer-runs">Sanitizers</a>)
    Merge --> PPA(<a href="#deb-package-builds"><tt>.deb</tt> packages</a>)
    PPA --> Snaps
    Snaps --> EndToEnd(<a href="#end-to-end-testing">End-to-end testing</a>)
