# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  # https://github.com/readthedocs/readthedocs.org/issues/9599
  apt_packages:
  - cmake
  - doxygen
  - graphviz
  - libboost-dev
  - libboost-iostreams-dev
  - libboost-program-options-dev
  - libboost-system-dev
  - libdrm-dev
  - libdisplay-info-dev
  - libegl-dev
  - libepoxy-dev
  - libfreetype-dev
  - libglib2.0-dev
  - libgles2-mesa-dev
  - libglm-dev
  - libinput-dev
  - liblttng-ust-dev
  - libwayland-dev
  - libxcb-composite0-dev
  - libxcb-randr0-dev
  - libxcb-res0-dev
  - libxcursor-dev
  - libxkbcommon-dev
  - libxml++2.6-dev
  - libyaml-cpp-dev
  - xsltproc
  jobs:
    post_checkout:
    - git fetch --unshallow
      # Cancel building pull requests when there aren't changed in the docs directory.
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- 'doc/' 'doc/sphinx/.readthedocs.yaml' 'include/' 'src/include/';
      then
        exit 183;
      fi
    post_install:
    - cmake -DBUILD_DOXYGEN=YES -DMIR_ENABLE_TESTS=NO -DMIR_PLATFORM=x11 .
    - cmake --build . --target doxygen

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: doc/sphinx/conf.py
  fail_on_warning: false

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/sphinx/requirements.txt
