# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # https://github.com/readthedocs/readthedocs.org/issues/9599
  apt_packages:
  - cmake
  - libboost-dev
  - libboost-iostreams-dev
  - libboost-filesystem-dev
  - libboost-program-options-dev
  - libboost-system-dev
  - libdrm-dev
  - libegl-dev
  - libepoxy-dev
  - libfreetype-dev
  - libglib2.0-dev
  - libgles2-mesa-dev
  - libglm-dev
  - libgoogle-glog-dev
  - libinput-dev
  - liblttng-ust-dev
  - libwayland-dev
  - libxcb-composite0-dev
  - libxcb-randr0-dev
  - libxcursor-dev
  - libxkbcommon-dev
  - libxml++2.6-dev
  - libyaml-cpp-dev
  - xsltproc
  jobs:
    post_checkout:
    - git fetch --unshallow
    post_install:
    - cmake -DMIR_ENABLE_TESTS=NO -DMIR_PLATFORM=x11 .
    - cmake --build . --target guides

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: doc/sphinx/conf.py
  fail_on_warning: false

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/sphinx/.sphinx/requirements.txt
