@startuml

hide members

' Miral
class miral.MirRunner
class miral.BasicWindowManager extends mir.shell.WindowManager


' Server
class mir.Server

' Scene
class mir.scene.SurfaceStack

' Graphics
class mir.graphics.MultiplexingDisplay
abstract class mir.graphics.DisplayPlatform
abstract class mir.graphics.Display
abstract class mir.graphics.DisplayBuffer
class mir.graphics.gbm.Display extends mir.graphics.DisplayPlatform
class mir.graphics.wayland.Display extends mir.graphics.DisplayPlatform
class mir.graphics.X.Display extends mir.graphics.DisplayPlatform
class mir.graphics.eglstrean.Display extends mir.graphics.DisplayPlatform

' Input
class mir.input.InputDispatcher
class mir.input.Platform
class mir.input.evdev.Platform extends mir.input.Platform
class mir.input.wayland.Platform extends mir.input.Platform
class mir.input.X.Platform extends mir.input.Platform

' Shell
class mir.shell.AbstractShell
class mir.shell.WindowManager

' Compositor
class mir.compositor.MultithreadedCompositor
class mir.compositor.ScreenShooter

' Renderer
class mir.renderer.RendererFactory
class mir.renderer.Renderer
class mir.renderer.gl.Renderer extends mir.renderer.Renderer

' Frontends
class mir.frontend.WaylandConnector
class mir.frontend.XWaylandConnector

' Forces miral on top of mir
miral.MirRunner --[hidden]-> mir.Server

' Relationships
mir.Server <-- mir.compositor.MultithreadedCompositor
mir.Server <-- mir.input.InputDispatcher
mir.Server <-- mir.frontend.XWaylandConnector
mir.Server <-- mir.frontend.WaylandConnector

miral.MirRunner <-- mir.Server
miral.MirRunner <- miral.BasicWindowManager
miral.BasicWindowManager "n" <- miral.WindowManagementPolicy

mir.compositor.MultithreadedCompositor <-- mir.renderer.RendererFactory
mir.compositor.MultithreadedCompositor <-- mir.scene.SurfaceStack

mir.renderer.RendererFactory <-- mir.renderer.Renderer
mir.graphics.MultiplexingDisplay "n" <-- mir.graphics.Display
mir.graphics.DisplayPlatform <-- mir.graphics.Display
mir.graphics.Display "n" <-- mir.graphics.DisplayBuffer

mir.frontend.WaylandConnector <-- mir.shell.AbstractShell
mir.frontend.XWaylandConnector <-- mir.shell.AbstractShell
mir.shell.AbstractShell <-- mir.scene.SurfaceStack
mir.shell.AbstractShell <-- mir.shell.WindowManager

mir.input.InputDispatcher <-- mir.input.Platform

mir.compositor.MultithreadedCompositor <-- mir.compositor.ScreenShooter
mir.compositor.ScreenShooter <-- mir.shell.AbstractShell

@enduml
