
classDiagram
    CompositorAuthor --> miral: Uses
    CompositorAuthor --> miroil: Uses
    CompositorAuthor --> mirwayland: Uses

    miral --> mirserver: Uses
    miroil --> mirserver: Uses
    mirwayland --> mirserver: Uses

    note for core "Universal"
    note for common "Universal"
    class core
    class common
