
classDiagram
    Server o-- Shell
    Server o-- Scene
    Server o-- Compositor
    Server o-- Seat
    Server o-- Display

    Shell --> miral: Ask for implementation of shell behavior
    Shell --> Scene: Updates
    Compositor --> Scene: Reads
    Compositor --> Display: To determine outputs
    Compositor --> RenderingPlatform: Renders using
    Compositor --> DisplayPlatform: Outputs to
    InputDispatcher <-- InputPlatform: Sends events to
    Seat <-- InputDispatcher: Sends events to
    Seat --> Shell: Sends events to
    FrontendWayland --> Shell: Makes requests to
    FrontendXWayland --> Shell: Makes request to
    Scene o-- IdleHub
    Scene o-- Clipboard
    Scene o-- SceneChangeNotifiers


    %%Server --> Core
    %%Server --> Common
