
classDiagram
    Shell --> Scene: Updates
    Server o-- Shell
    Server o-- Scene
    Server o-- Compositor
    Server o-- Seat
    Server o-- Display

    Shell --> miral: Get shell behavior
    Compositor --> Scene: Get renderables
    Compositor --> Display: Get outputs
    Compositor --> RenderingPlatform: Handles rendering
    Compositor --> DisplayPlatform: Outputs image to
    InputDispatcher <-- InputPlatform: Sends events to
    Seat <-- InputDispatcher: Sends events to
    Seat --> Shell: Sends events to
    FrontendWayland --> Shell: Makes requests to
    FrontendXWayland --> Shell: Makes request to
    Scene o-- IdleHub
    Scene o-- Clipboard
    Scene o-- SceneChangeNotifiers


    %%Server --> Core
    %%Server --> Common
