name: dev
description: |
  A development environment for Mir.
  Provides a Ubuntu 26.04 base with VS Code Remote, GitHub Copilot, and the Mir project SDK.
  Includes actions for configuring (cmake), building (build), and compiling with cache support (ccache),
  as well as documentation generation (doc), exposed via a tunnel on `localhost:8000`.

  Connect the `desktop` interface (`workshop connect dev/mir:desktop`) to run the built server with `workshop exec <executable>` displayed on the host.
base: ubuntu@26.04
sdks:
- name: vscode-remote
- name: copilot
- name: project-mir
- name: system
  plugs:
    doc:
      interface: tunnel
      endpoint: localhost:8000
actions:
  cmake: |
    set -xeu
    cmake ~/build "$@"

  build: |
    set -xeu
    cmake --build ~/build "$@"

  test: |
    set -xeu
    cmake --build ~/build
    VERBOSE=1 ARGS="-V" cmake --build ~/build --target ptest "$@"

  doc: |
    set -xeu

    if [ "$#" -gt "0" ]; then
      target="$1"
      shift
    fi

    cmake --build ~/build --target "doc-${target:-run}" "$@"

  ccache: ccache "$@"
