classDiagram
    miral --> mircore
    mirwayland --> mircore

    Compositor --> miral
    Compositor --> mirwayland

    class miral["miral (main APIs)"]
    class mirwayland["mirwayland (Extension APIs)"]
