
classDiagram
    mirserver --> mircore
    mircommon --> mircore
    mirplatform --> mircore
    mirwayland --> mircore
    miral --> mircore

    mirserver --> mirplatform
    mirplatform --> mircommon
    miral --> mircommon
    mirserver --> mircommon
    mirwayland --> mircommon


    miral --> mirserver
    mirwayland --> mirserver
    miroil --> mirserver

    Compositor --> miral
    Compositor --> mirwayland
    Compositor --> miroil

    Compositor --> mircore

    miroil --> mircore
    class miroil["miroil (for Lomiri)"]
    style miroil color:#aaa
    namespace MirEngine {
        class mirserver
        class mircommon
        class mirplatform
    }

