classDiagram
    mircommon --> mircore
    mirwayland --> mircore
    miral --> mircore
    miroil --> mircore
    mirserver --> mircore
    input~X~ --> mircore
    display~X~ --> mircore
    rendering~X~ --> mircore

    mirwayland --> mircommon
    mirserver --> mircommon
    miral --> mircommon
    miroil --> mircommon
    mirplatform --> mircommon

    mirserver --> mirwayland

    mirserver --> mirplatform
    input~X~ --> mirplatform
    display~X~ --> mirplatform
    rendering~X~ --> mirplatform

    mirserver --> input~X~: dynamically loads
    mirserver --> display~X~: dynamically loads
    mirserver --> rendering~X~: dynamically loads

    miral --> mirserver
    miroil --> mirserver

    namespace platform {
        class input~X~
        class display~X~
        class rendering~X~
    }
