flowchart
    miral ---> mirserver
    miral ---> mircommon
    miroil ---> mirserver
    miroil --> mircommon
    mirserver --> mirplatform
    mirserver --> mircommon
    mirserver --> mirserverlttng
    mirserver --> mircore
    mirserver --->|dynamically loads|graphics_X
    mirserver --->|dynamically loads|input_X
    mirwayland --> mircore
    graphics_X --> mirplatform
    graphics_X --> mircommon
    graphics_X --> mircore
    input_X --> mirplatform
    input_X --> mircommon
    input_X --> mircore