
classDiagram
    namespace platforms {
        class DisplayPlatform
        class RenderingPlatform
        class InputPlatform
    }

    DisplayPlatform --> mirplatform
    RenderingPlatform --> mirplatform
    InputPlatform --> mirplatform

    Seat <-- InputDispatcher: Sends events to
    FrontendXWayland --> Shell: Makes request to
    FrontendWayland --> Shell: Makes requests to
    Seat --> Shell: Sends events to

    Compositor --> Display: Get outputs
    Shell --> Scene: Updates
    Compositor --> Scene: Get renderables

    InputDispatcher <-- InputPlatform: Sends events to
    Compositor --> RenderingPlatform: Handles rendering
    Compositor --> DisplayPlatform: Outputs image to

    <<Controller>> Shell
    <<Model>> Scene
    <<View>> Compositor

    Shell o-- WindowManagementStrategy
    class WindowManagementStrategy["WindowManagementStrategy\n (supplied by miral)"]
