#!/bin/bash

set -ex

VERSION_RE='v(([0-9]+)\.([0-9]+)\.([0-9]+))'  # version format vX.Y.Z (note not matching start/end)
RELEASE_RE="^(refs/heads/)?release/[0-9]+\.[0-9]+\$|^(refs/tags/)?${VERSION_RE}\$"  # release branch or tag

# by default, match the dev tag
DESCRIBE_FLAGS=( --match=*-dev )

while [ $# -gt 0 ]
do
  if [ "$1" == "--skip-checks" ]
  then
    skip_checks=true
  fi
  if [ "$1" == "--release-tag" ]
  then
    shift
    RELEASE_TAG=$1
    DESCRIBE_FLAGS=( --match=v*.*.* )
  fi
  shift
done

GIT_BRANCH=${GITHUB_REF-$( git rev-parse --abbrev-ref HEAD )}
if ! [ -v RELEASE_TAG ]; then
  RELEASE_TAG="HEAD"
  # if we're on a release branch or tag, exclude dev tags instead
  if [[ "${GIT_BRANCH}" =~ ${RELEASE_RE} ]]; then
    DESCRIBE_FLAGS=( --exclude=*-dev )
  fi
fi

if [ ! -e tools/make_release_tarball  -o  "$1" != "" ]
then
  echo "Handy script for creating tarball: Use from the checkout directory"
  exit 0
fi

set -e
TAG=$( git describe --tags --abbrev=0 "${DESCRIBE_FLAGS[@]}" "${RELEASE_TAG}")
if [[ "${TAG}" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-(dev|rc))?$ ]]; then
  VERSION_MAJOR=${BASH_REMATCH[1]}
  VERSION_MINOR=${BASH_REMATCH[2]}
  VERSION_PATCH=${BASH_REMATCH[3]}
  VERSION_SUFFIX=${BASH_REMATCH[5]}
else
  echo "Error: Could not determine version for ${RELEASE_TAG} )"
  exit 1
fi

VERSIONED_NAME=mir-$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH${VERSION_SUFFIX:+~$VERSION_SUFFIX}

SCRATCH_DIR=$(mktemp -d)
BUILD_DIR=$(mktemp -d)
INSTALL_DIR=$(mktemp -d)

function cleanup() {
	ARG=$?
	[ -d $SCRATCH_DIR ] && rm -r $SCRATCH_DIR
	[ -d $BUILD_DIR ] && rm -r $BUILD_DIR
	[ -d $INSTALL_DIR ] && rm -r $INSTALL_DIR
	exit $ARG
}

trap cleanup EXIT

echo "Generating Mir tarball…"
git archive --format=tar --prefix=$VERSIONED_NAME/ $RELEASE_TAG | xz -9 > $SCRATCH_DIR/$VERSIONED_NAME.tar.xz

if [ ! -v skip_checks ]
then
  (cd $SCRATCH_DIR; tar xvJf $SCRATCH_DIR/$VERSIONED_NAME.tar.xz)

  echo "Testing that the tarball is buildable"
  (cd $BUILD_DIR ; cmake $SCRATCH_DIR/$VERSIONED_NAME )
  make -C $BUILD_DIR -j $(nproc)

  echo "Testing that the tarball is installable"
  make -C $BUILD_DIR install DESTDIR=$INSTALL_DIR
fi

mv $SCRATCH_DIR/$VERSIONED_NAME.tar.xz .
echo "$VERSIONED_NAME.tar.xz successfully created and tested"
