/*
 * Copyright © 2015 Canonical Ltd.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored By: Andreas Pokorny <andreas.pokorny@canonical.com>
 */

#ifndef MIR_PP_FOREACH_H_
#define MIR_PP_FOREACH_H_

// per element apply of a macros - single parameter version
#define MIR_FOREACH_UNROLL_1(WHAT, X) WHAT(X)
#define MIR_FOREACH_UNROLL_2(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_1(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_3(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_2(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_4(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_3(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_5(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_4(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_6(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_5(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_7(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_6(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_8(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_7(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_9(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_8(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_10(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_9(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_11(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_10(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_12(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_11(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_13(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_12(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_14(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_13(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_15(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_14(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_16(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_15(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_17(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_16(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_18(WHAT, X, ...) WHAT(X)MIR_FOREACH_UNROLL_17(WHAT, __VA_ARGS__)


// per element apply of a macros - tuple parameter version
#define MIR_FOREACH_UNROLL_TUPLE_1(WHAT, X) WHAT X
#define MIR_FOREACH_UNROLL_TUPLE_2(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_1(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_3(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_2(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_4(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_3(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_5(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_4(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_6(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_5(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_7(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_6(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_8(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_7(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_9(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_8(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_10(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_9(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_11(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_10(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_12(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_11(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_13(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_12(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_14(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_13(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_15(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_14(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_16(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_15(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_17(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_16(WHAT, __VA_ARGS__)
#define MIR_FOREACH_UNROLL_TUPLE_18(WHAT, X, ...) WHAT X MIR_FOREACH_UNROLL_TUPLE_17(WHAT, __VA_ARGS__)
//... repeat as needed

#define MIR_FOR_EACH_GET_MACRO(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,NAME,...) NAME

/**
 * Invoke \a action for each parameter.
 * The first parameter has to be a macro that requires one parameter
 */
#define MIR_FOR_EACH(action,...) \
  MIR_FOR_EACH_GET_MACRO(__VA_ARGS__,MIR_FOREACH_UNROLL_18,MIR_FOREACH_UNROLL_17,MIR_FOREACH_UNROLL_16,MIR_FOREACH_UNROLL_15,MIR_FOREACH_UNROLL_14,MIR_FOREACH_UNROLL_13,MIR_FOREACH_UNROLL_12,MIR_FOREACH_UNROLL_11,MIR_FOREACH_UNROLL_10,MIR_FOREACH_UNROLL_9,MIR_FOREACH_UNROLL_8,MIR_FOREACH_UNROLL_7,MIR_FOREACH_UNROLL_6,MIR_FOREACH_UNROLL_5,MIR_FOREACH_UNROLL_4,MIR_FOREACH_UNROLL_3,MIR_FOREACH_UNROLL_2,MIR_FOREACH_UNROLL_1)(action,__VA_ARGS__)

/**
 * Invoke \a action for each parameter tuple.
 */
#define MIR_FOR_EACH_TUPLE(action,...) \
  MIR_FOR_EACH_GET_MACRO(__VA_ARGS__,MIR_FOREACH_UNROLL_TUPLE_18,MIR_FOREACH_UNROLL_TUPLE_17,MIR_FOREACH_UNROLL_TUPLE_16,MIR_FOREACH_UNROLL_TUPLE_15,MIR_FOREACH_UNROLL_TUPLE_14,MIR_FOREACH_UNROLL_TUPLE_13,MIR_FOREACH_UNROLL_TUPLE_12,MIR_FOREACH_UNROLL_TUPLE_11,MIR_FOREACH_UNROLL_TUPLE_10,MIR_FOREACH_UNROLL_TUPLE_9,MIR_FOREACH_UNROLL_TUPLE_8,MIR_FOREACH_UNROLL_TUPLE_7,MIR_FOREACH_UNROLL_TUPLE_6,MIR_FOREACH_UNROLL_TUPLE_5,MIR_FOREACH_UNROLL_TUPLE_4,MIR_FOREACH_UNROLL_TUPLE_3,MIR_FOREACH_UNROLL_TUPLE_2,MIR_FOREACH_UNROLL_TUPLE_1)(action,__VA_ARGS__)

#endif
