name: mir-libs
base: core22
summary: The fast, open and secure display server for any device - build environment
description: |
  Mir is a display server running on linux systems, with a focus on efficiency,
  robust operation and a well-defined driver model.

  This snap contains the build environment necessary to build Mir display servers.

confinement: strict
adopt-info: mir

parts:
  mir:
    plugin: cmake
    source: .
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DMIR_ENABLE_WLCS_TESTS=OFF
    - -DMIR_PLATFORM='gbm-kms;eglstream-kms;x11;wayland'
    build-packages:
    - build-essential
    - eglexternalplatform-dev
    - git
    - libboost-date-time-dev
    - libboost-filesystem-dev
    - libboost-iostreams-dev
    - libboost-program-options-dev
    - libcapnp-dev
    - libdrm-dev
    - libegl1-mesa-dev
    - libepoxy-dev
    - libfreetype6-dev
    - libgbm-dev
    - libglm-dev
    - libgoogle-glog-dev
    - libgtest-dev
    - libinput-dev
    - liblttng-ust-dev
    - libnvidia-egl-wayland-dev
    - libudev-dev
    - libumockdev-dev
    - libwayland-dev
    - libxcb-composite0-dev
    - libx11-xcb-dev
    - libxcursor-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libxml++2.6-dev
    - libyaml-cpp-dev
    - nettle-dev
    - python3-pil
    - systemtap-sdt-dev
    stage-packages:
    - libboost-filesystem1.74.0
    - libboost-iostreams1.74.0
    - libboost-program-options1.74.0
    - libcapnp-0.8.0
    - libdrm2
    - libegl1
    - libepoxy0
    - libevdev2
    - libfreetype6
    - libgbm1
    - libgflags2.2
    - libgles2
    - libglibmm-2.4-1v5
    - libglvnd0
    - libgoogle-glog0v5
    - libgudev-1.0-0
    - libicu70
    - libinput10
    - liblttng-ust1
    - libmtdev1
    - libnuma1
    - libnvidia-egl-wayland1
    - libpng16-16
    - libsigc++-2.0-0v5
    - libunwind8
    - liburcu8
    - libwacom9
    - libwayland-client0
    - libwayland-egl1
    - libwayland-server0
    - libx11-6
    - libxau6
    - libxcb-composite0
    - libxcb-render0
    - libxcb-xfixes0
    - libxcb1
    - libx11-xcb1
    - libxcursor1
    - libxdmcp6
    - libxfixes3
    - libxkbcommon0
    - libxkbcommon-x11-0
    - libxml++2.6-2v5
    - libxml2
    - libxrender1
    - libyaml-cpp0.7
    override-pull: |
      craftctl default
      craftctl set version=$( git describe | awk -F- '{ gsub(/^v/, "", $1); printf $1; if ($2) { printf "+dev" $2 "-" $3 } }' )
      craftctl set grade=$( [[ $( git describe ) =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo stable || echo devel )
