name: mir-libs
base: core24
summary: The fast, open and secure display server for any device - build environment
description: |
  Mir is a display server running on linux systems, with a focus on efficiency,
  robust operation and a well-defined driver model.

  This snap contains the build environment necessary to build Mir display servers.

confinement: strict
version: testing
grade: devel

parts:
  mir:
    plugin: cmake
    source: .
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DMIR_ENABLE_WLCS_TESTS=OFF
    - -DMIR_PLATFORM='atomic-kms;gbm-kms;eglstream-kms;x11;wayland'
    build-packages:
    - build-essential
    - eglexternalplatform-dev
    - git
    - libboost-date-time-dev
    - libboost-filesystem-dev
    - libboost-iostreams-dev
    - libboost-program-options-dev
    - libdrm-dev
    - libegl1-mesa-dev
    - libepoxy-dev
    - libfreetype-dev
    - libgbm-dev
    - libglm-dev
    - libgtest-dev
    - libinput-dev
    - liblttng-ust-dev
    - libnvidia-egl-wayland-dev
    - libudev-dev
    - libumockdev-dev
    - libwayland-dev
    - libxcb-composite0-dev
    - libxcb-randr0-dev
    - libx11-xcb-dev
    - libxcursor-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libxml++2.6-dev
    - libyaml-cpp-dev
    - nettle-dev
    - python3-pil
    - systemtap-sdt-dev
    - libapparmor-dev
    - wlcs
    - libpixman-1-dev
    stage-packages:
    - libboost-filesystem1.83.0
    - libboost-iostreams1.83.0
    - libboost-program-options1.83.0
    - libdrm2
    - libegl1
    - libepoxy0
    - libevdev2
    - libfreetype6
    - libgbm1
    - libgles2
    - libglib2.0-0t64
    - libglibmm-2.4-1t64
    - libglvnd0
    - libgudev-1.0-0
    - libicu74
    - libinput10
    - liblttng-ust1t64
    - libmtdev1t64
    - libnuma1
    - libnvidia-egl-wayland1
    - libpng16-16t64
    - libsigc++-2.0-0v5
    - liburcu8t64
    - libwacom9
    - libwayland-client0
    - libwayland-egl1
    - libwayland-server0
    - libx11-6
    - libxau6
    - libxcb-composite0
    - libxcb-randr0
    - libxcb-render0
    - libxcb-xfixes0
    - libxcb1
    - libx11-xcb1
    - libxcursor1
    - libxdmcp6
    - libxfixes3
    - libxkbcommon0
    - libxkbcommon-x11-0
    - libxml++2.6-2v5
    - libxml2
    - libxrender1
    - libyaml-cpp0.8
    - libapparmor1
