/*
 * AUTOGENERATED - DO NOT EDIT
 *
 * This file is generated from mir-trusted-prompt-sessions-v1.xml
 * To regenerate, run the “refresh-wayland-wrapper” target.
 */

#ifndef MIR_FRONTEND_WAYLAND_MIR_TRUSTED_PROMPT_SESSIONS_V1_XML_WRAPPER
#define MIR_FRONTEND_WAYLAND_MIR_TRUSTED_PROMPT_SESSIONS_V1_XML_WRAPPER

#include <experimental/optional>

#include "mir/fd.h"
#include <wayland-server-core.h>

#include "mir/wayland/wayland_base.h"

namespace mir
{
namespace wayland
{

class ZmirTrustedPromptSessionsManagerV1;
class ZmirTrustedPromptSessionV1;

class ZmirTrustedPromptSessionsManagerV1 : public Resource
{
public:
    static char const constexpr* interface_name = "zmir_trusted_prompt_sessions_manager_v1";

    static ZmirTrustedPromptSessionsManagerV1* from(struct wl_resource*);

    ZmirTrustedPromptSessionsManagerV1(struct wl_resource* resource, Version<1>);
    virtual ~ZmirTrustedPromptSessionsManagerV1();

    void destroy_wayland_object() const;

    struct wl_client* const client;
    struct wl_resource* const resource;

    struct Thunks;

    static bool is_instance(wl_resource* resource);

    class Global : public wayland::Global
    {
    public:
        Global(wl_display* display, Version<1>);

        auto interface_name() const -> char const* override;

    private:
        virtual void bind(wl_resource* new_zmir_trusted_prompt_sessions_manager_v1) = 0;
        friend ZmirTrustedPromptSessionsManagerV1::Thunks;
    };

private:
    virtual void create_session(struct wl_resource* id) = 0;
    virtual void destroy() = 0;
};

class ZmirTrustedPromptSessionV1 : public Resource
{
public:
    static char const constexpr* interface_name = "zmir_trusted_prompt_session_v1";

    static ZmirTrustedPromptSessionV1* from(struct wl_resource*);

    ZmirTrustedPromptSessionV1(struct wl_resource* resource, Version<1>);
    virtual ~ZmirTrustedPromptSessionV1();

    void destroy_wayland_object() const;

    struct wl_client* const client;
    struct wl_resource* const resource;

    struct Thunks;

    static bool is_instance(wl_resource* resource);

private:
    virtual void destroy() = 0;
};

}
}

#endif // MIR_FRONTEND_WAYLAND_MIR_TRUSTED_PROMPT_SESSIONS_V1_XML_WRAPPER
