/*
 * AUTOGENERATED - DO NOT EDIT
 *
 * This file is generated from mir-trusted-prompt-sessions-v1.xml
 * To regenerate, run the “refresh-wayland-wrapper” target.
 */

#include "mir-trusted-prompt-sessions-v1_wrapper.h"

#include <boost/throw_exception.hpp>
#include <boost/exception/diagnostic_information.hpp>

#include <wayland-server-core.h>

#include "mir/log.h"

namespace mir
{
namespace wayland
{
extern struct wl_interface const zmir_trusted_prompt_session_v1_interface_data;
extern struct wl_interface const zmir_trusted_prompt_sessions_manager_v1_interface_data;
}
}

namespace mw = mir::wayland;

namespace
{
struct wl_interface const* all_null_types [] {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr};
}

// ZmirTrustedPromptSessionsManagerV1

struct mw::ZmirTrustedPromptSessionsManagerV1::Thunks
{
    static int const supported_version;

    static void create_session_thunk(struct wl_client* client, struct wl_resource* resource, uint32_t id)
    {
        auto me = static_cast<ZmirTrustedPromptSessionsManagerV1*>(wl_resource_get_user_data(resource));
        wl_resource* id_resolved{
            wl_resource_create(client, &zmir_trusted_prompt_session_v1_interface_data, wl_resource_get_version(resource), id)};
        if (id_resolved == nullptr)
        {
            wl_client_post_no_memory(client);
            BOOST_THROW_EXCEPTION((std::bad_alloc{}));
        }
        try
        {
            me->create_session(id_resolved);
        }
        catch(ProtocolError const& err)
        {
            wl_resource_post_error(err.resource(), err.code(), "%s", err.message());
        }
        catch(...)
        {
            internal_error_processing_request(client, "ZmirTrustedPromptSessionsManagerV1::create_session()");
        }
    }

    static void destroy_thunk(struct wl_client* client, struct wl_resource* resource)
    {
        auto me = static_cast<ZmirTrustedPromptSessionsManagerV1*>(wl_resource_get_user_data(resource));
        try
        {
            me->destroy();
        }
        catch(ProtocolError const& err)
        {
            wl_resource_post_error(err.resource(), err.code(), "%s", err.message());
        }
        catch(...)
        {
            internal_error_processing_request(client, "ZmirTrustedPromptSessionsManagerV1::destroy()");
        }
    }

    static void resource_destroyed_thunk(wl_resource* resource)
    {
        delete static_cast<ZmirTrustedPromptSessionsManagerV1*>(wl_resource_get_user_data(resource));
    }

    static void bind_thunk(struct wl_client* client, void* data, uint32_t version, uint32_t id)
    {
        auto me = static_cast<ZmirTrustedPromptSessionsManagerV1::Global*>(data);
        auto resource = wl_resource_create(
            client,
            &zmir_trusted_prompt_sessions_manager_v1_interface_data,
            std::min((int)version, Thunks::supported_version),
            id);
        if (resource == nullptr)
        {
            wl_client_post_no_memory(client);
            BOOST_THROW_EXCEPTION((std::bad_alloc{}));
        }
        try
        {
            me->bind(resource);
        }
        catch(...)
        {
            internal_error_processing_request(client, "ZmirTrustedPromptSessionsManagerV1 global bind");
        }
    }

    static struct wl_interface const* create_session_types[];
    static struct wl_message const request_messages[];
    static void const* request_vtable[];
};

int const mw::ZmirTrustedPromptSessionsManagerV1::Thunks::supported_version = 1;

mw::ZmirTrustedPromptSessionsManagerV1::ZmirTrustedPromptSessionsManagerV1(struct wl_resource* resource, Version<1>)
    : client{wl_resource_get_client(resource)},
      resource{resource}
{
    if (resource == nullptr)
    {
        BOOST_THROW_EXCEPTION((std::bad_alloc{}));
    }
    wl_resource_set_implementation(resource, Thunks::request_vtable, this, &Thunks::resource_destroyed_thunk);
}

mw::ZmirTrustedPromptSessionsManagerV1::~ZmirTrustedPromptSessionsManagerV1()
{
    wl_resource_set_implementation(resource, nullptr, nullptr, nullptr);
}

bool mw::ZmirTrustedPromptSessionsManagerV1::is_instance(wl_resource* resource)
{
    return wl_resource_instance_of(resource, &zmir_trusted_prompt_sessions_manager_v1_interface_data, Thunks::request_vtable);
}

void mw::ZmirTrustedPromptSessionsManagerV1::destroy_wayland_object() const
{
    wl_resource_destroy(resource);
}

mw::ZmirTrustedPromptSessionsManagerV1::Global::Global(wl_display* display, Version<1>)
    : wayland::Global{
          wl_global_create(
              display,
              &zmir_trusted_prompt_sessions_manager_v1_interface_data,
              Thunks::supported_version,
              this,
              &Thunks::bind_thunk)}
{
}

auto mw::ZmirTrustedPromptSessionsManagerV1::Global::interface_name() const -> char const*
{
    return ZmirTrustedPromptSessionsManagerV1::interface_name;
}

struct wl_interface const* mw::ZmirTrustedPromptSessionsManagerV1::Thunks::create_session_types[] {
    &zmir_trusted_prompt_session_v1_interface_data};

struct wl_message const mw::ZmirTrustedPromptSessionsManagerV1::Thunks::request_messages[] {
    {"create_session", "n", create_session_types},
    {"destroy", "", all_null_types}};

void const* mw::ZmirTrustedPromptSessionsManagerV1::Thunks::request_vtable[] {
    (void*)Thunks::create_session_thunk,
    (void*)Thunks::destroy_thunk};

mw::ZmirTrustedPromptSessionsManagerV1* mw::ZmirTrustedPromptSessionsManagerV1::from(struct wl_resource* resource)
{
    if (wl_resource_instance_of(resource, &zmir_trusted_prompt_sessions_manager_v1_interface_data, ZmirTrustedPromptSessionsManagerV1::Thunks::request_vtable))
    {
        return static_cast<ZmirTrustedPromptSessionsManagerV1*>(wl_resource_get_user_data(resource));
    }
    return nullptr;
}

// ZmirTrustedPromptSessionV1

struct mw::ZmirTrustedPromptSessionV1::Thunks
{
    static int const supported_version;

    static void destroy_thunk(struct wl_client* client, struct wl_resource* resource)
    {
        auto me = static_cast<ZmirTrustedPromptSessionV1*>(wl_resource_get_user_data(resource));
        try
        {
            me->destroy();
        }
        catch(ProtocolError const& err)
        {
            wl_resource_post_error(err.resource(), err.code(), "%s", err.message());
        }
        catch(...)
        {
            internal_error_processing_request(client, "ZmirTrustedPromptSessionV1::destroy()");
        }
    }

    static void resource_destroyed_thunk(wl_resource* resource)
    {
        delete static_cast<ZmirTrustedPromptSessionV1*>(wl_resource_get_user_data(resource));
    }

    static struct wl_message const request_messages[];
    static void const* request_vtable[];
};

int const mw::ZmirTrustedPromptSessionV1::Thunks::supported_version = 1;

mw::ZmirTrustedPromptSessionV1::ZmirTrustedPromptSessionV1(struct wl_resource* resource, Version<1>)
    : client{wl_resource_get_client(resource)},
      resource{resource}
{
    if (resource == nullptr)
    {
        BOOST_THROW_EXCEPTION((std::bad_alloc{}));
    }
    wl_resource_set_implementation(resource, Thunks::request_vtable, this, &Thunks::resource_destroyed_thunk);
}

mw::ZmirTrustedPromptSessionV1::~ZmirTrustedPromptSessionV1()
{
    wl_resource_set_implementation(resource, nullptr, nullptr, nullptr);
}

bool mw::ZmirTrustedPromptSessionV1::is_instance(wl_resource* resource)
{
    return wl_resource_instance_of(resource, &zmir_trusted_prompt_session_v1_interface_data, Thunks::request_vtable);
}

void mw::ZmirTrustedPromptSessionV1::destroy_wayland_object() const
{
    wl_resource_destroy(resource);
}

struct wl_message const mw::ZmirTrustedPromptSessionV1::Thunks::request_messages[] {
    {"destroy", "", all_null_types}};

void const* mw::ZmirTrustedPromptSessionV1::Thunks::request_vtable[] {
    (void*)Thunks::destroy_thunk};

mw::ZmirTrustedPromptSessionV1* mw::ZmirTrustedPromptSessionV1::from(struct wl_resource* resource)
{
    if (wl_resource_instance_of(resource, &zmir_trusted_prompt_session_v1_interface_data, ZmirTrustedPromptSessionV1::Thunks::request_vtable))
    {
        return static_cast<ZmirTrustedPromptSessionV1*>(wl_resource_get_user_data(resource));
    }
    return nullptr;
}

namespace mir
{
namespace wayland
{

struct wl_interface const zmir_trusted_prompt_sessions_manager_v1_interface_data {
    mw::ZmirTrustedPromptSessionsManagerV1::interface_name,
    mw::ZmirTrustedPromptSessionsManagerV1::Thunks::supported_version,
    2, mw::ZmirTrustedPromptSessionsManagerV1::Thunks::request_messages,
    0, nullptr};

struct wl_interface const zmir_trusted_prompt_session_v1_interface_data {
    mw::ZmirTrustedPromptSessionV1::interface_name,
    mw::ZmirTrustedPromptSessionV1::Thunks::supported_version,
    1, mw::ZmirTrustedPromptSessionV1::Thunks::request_messages,
    0, nullptr};

}
}
