[package]
name = "mir_platforms_evdev"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx.workspace = true

[build-dependencies]
cxx-build.workspace = true
