name: Main Documentation Checks

on:
  pull_request:
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  documentation-checks:
    permissions:
      contents: read
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@aaeaf091e8f55145184ad897cb9834f224bd31de # main @ 2026.02.11
    with:
      working-directory: doc/sphinx
      linkcheck-target: linkcheck-with-dependencies
