name: documentation-checks

on:
  pull_request:
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      should-run: ${{ steps.filter.outputs.documentation }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: .github/filters.yaml

  spelling-check:
    name: ${{ needs.check-paths.outputs.should-run == 'true' && 'Documentation spelling check' || 'Documentation spelling check / Check spelling in the documentation' }}
    needs: [check-paths]
    if: needs.check-paths.outputs.should-run == 'true'
    permissions:
      contents: read
    uses: canonical/documentation-workflows/.github/workflows/spelling-check.yaml@aaeaf091e8f55145184ad897cb9834f224bd31de # main @ 2026.02.11
    with:
      working-directory: doc/sphinx

  inclusive-language-check:
    name: ${{ needs.check-paths.outputs.should-run == 'true' && 'Documentation inclusive language check' || 'Documentation inclusive language check / Check for inclusive language in the documentation' }}
    needs: [check-paths]
    if: needs.check-paths.outputs.should-run == 'true'
    permissions:
      contents: read
    uses: canonical/documentation-workflows/.github/workflows/inclusive-language-check.yaml@aaeaf091e8f55145184ad897cb9834f224bd31de # main @ 2026.02.11
    with:
      working-directory: doc/sphinx

  link-check:
    name: ${{ needs.check-paths.outputs.should-run == 'true' && 'Documentation link check' || 'Documentation link check / Check links in the documentation' }}
    needs: [check-paths]
    if: needs.check-paths.outputs.should-run == 'true'
    permissions:
      contents: read
    uses: canonical/documentation-workflows/.github/workflows/link-check.yaml@aaeaf091e8f55145184ad897cb9834f224bd31de # main @ 2026.02.11
    with:
      working-directory: doc/sphinx
      linkcheck-target: linkcheck-with-dependencies
