name: VKMS

on:
  push:
    branches:
    - main
    - release/[0-9]+.[0-9]+
    tags:
    - v[0-9]+[0-9]+.[0-9]+
  merge_group:
    types: [checks_requested]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.run_id }}
  cancel-in-progress: true

jobs:
  VKMS_Test:
    runs-on: [self-hosted, Linux, X64, large]

    steps:
    - name: Test vkms permissions
      run: |
        sudo apt-get -y install linux-modules-extra-$(uname -r) mesa-utils drm-info
        echo "Attempting to modprobe vkms"
        sudo modprobe -v vkms
        lsmod
        echo "So, what's in /dev/dri?"
        ls -la /dev/dri
        echo
        echo "Also, how about eglinfo?"
        eglinfo
        echo "Huh."
        drm_info

  VKMS_Test_On_GH_Runners:
    runs-on: ubuntu-latest

    steps:
    - name: Test vkms permissions
      run: |
        sudo apt-get -y install linux-modules-extra-$(uname -r) mesa-utils drm-info
        echo "Attempting to modprobe vkms"
        sudo modprobe -v vkms
        lsmod
        echo "So, what's in /dev/dri?"
        ls -la /dev/dri
        echo
        echo "Also, how about eglinfo?"
        sudo eglinfo
        echo "Huh."
        sudo drm_info
